name: 'QMS worker'
description: 'Handles QMS docs updates'
inputs:
  qms_pat:
    description: 'QMS Personal Access Token'
    required: true
  target_repo:
    description: 'QMS Target repository to update (owner/repo)'
    required: true
  openai_key:
    description: 'OpenAI API Key'
    required: true
  instruction:
    description: 'Instruction to update the file'
    required: true
  issue_title:
    description: 'Issue title'
    required: false
  issue_body:
    description: 'Issue body'
    required: false
  issue_url:
    description: 'Issue url'
    required: false
  pr_title:
    description: 'Pull request title'
    required: false
  pr_body:
    description: 'Pull request body'
    required: false
  pr_url:
    description: 'Pull request url'
    required: false
outputs:
  result:
    description: 'The result of the QMS worker action'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.qms_pat }}
    - ${{ inputs.target_repo }}
    - ${{ inputs.openai_key }}
    - ${{ inputs.instruction }}
    - ${{ inputs.issue_title }}
    - ${{ inputs.issue_body }}
    - ${{ inputs.issue_url }}
    - ${{ inputs.pr_title }}
    - ${{ inputs.pr_body }}
    - ${{ inputs.pr_url }}
