name: 'Square Number Action'
description: 'Squares a given number'
inputs:
  number:
    description: 'Number to square'
    required: true
    default: '5'
outputs:
  result:
    description: 'The squared number'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.number }}