name: 'QMS worker'
description: 'Handles QMS docs updates'
inputs:
  qms_pat:
    description: 'QMS Personal Access Token'
    required: true
  target_repo:
    description: 'QMS Target repository to update (owner/repo)'
    required: true
  openai_key:
    description: 'OpenAI API Key'
    required: true
outputs:
  result:
    description: 'The squared number'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.qms_pat }}
    - ${{ inputs.target_repo }}
    - ${{ inputs.openai_key }}
